// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/team-photos/BentoGrid.tsx": () => import("../components/mockups/team-photos/BentoGrid.tsx"),
  "./components/mockups/team-photos/HorizontalStrip.tsx": () => import("../components/mockups/team-photos/HorizontalStrip.tsx"),
  "./components/mockups/team-photos/UniformGrid.tsx": () => import("../components/mockups/team-photos/UniformGrid.tsx")
};
